// schemas.ts
export const ENTITY_SCHEMAS: Record<
  string,
  { label: string; key: string; fields: { key: string; label: string }[] }
> = {
  students: {
    label: "Học viên",
    key: "students",
    fields: [
      { key: "cccd", label: "CCCD / CMND" },
      { key: "lop", label: "Lớp" },
      { key: "maHocVien", label: "Mã học viên" },
      { key: "hoTen", label: "Họ và tên" },
      { key: "maNganh", label: "Mã ngành" },
      { key: "tenNganh", label: "Tên ngành" },
      { key: "loaiChuongTrinh", label: "Loại chương trình" },
      { key: "trinhDo", label: "Trình độ" },
      { key: "ngayNhapHoc", label: "Ngày nhập học" },
      { key: "trangThai", label: "Trạng thái học" },
      { key: "ngaySinh", label: "Ngày sinh" },
      { key: "gioiTinh", label: "Giới tính" },
      { key: "email", label: "Email" },
      { key: "tenLuanVan", label: "Tên luận văn / Đề tài" },
      { key: "gvHuongDan1", label: "GV hướng dẫn 1" },
      { key: "gvHuongDan2", label: "GV hướng dẫn 2" },
      { key: "ngayQD", label: "Ngày QĐ giao đề tài / Đề cương" },
      { key: "trangThaiLv", label: "Trạng thái luận văn" },
      { key: "ngayBaoVe", label: "Ngày bảo vệ" },
      { key: "ngayTotNghiep", label: "Ngày tốt nghiệp / QĐTN" },
    ],
  },
  thesis: {
    label: "Luận văn",
    key: "thesis",
    fields: [
      { key: "maHocVien", label: "Mã học viên" },
      { key: "hoTen", label: "Họ tên học viên / Tác giả" },
      { key: "tenLuanVan", label: "Tên luận văn / Nhan đề" },
      { key: "gvHuongDan1", label: "GV hướng dẫn 1" },
      { key: "gvHuongDan2", label: "GV hướng dẫn 2" },
      { key: "ngayQD", label: "Ngày QĐ giao đề tài" },
      { key: "trangThai", label: "Trạng thái luận văn" },
      { key: "ngayBaoVe", label: "Ngày bảo vệ" },
      { key: "ngayTotNghiep", label: "Ngày tốt nghiệp" },
      { key: "tenNganh", label: "Chuyên ngành" },
      { key: "namXuatBan", label: "Năm xuất bản" },
    ],
  },
  teachers: {
    label: "Giảng viên",
    key: "teachers",
    fields: [
      { key: "shcc", label: "Mã giảng viên / SHCC" },
      { key: "hoten", label: "Họ và tên" },
      { key: "gioitinh", label: "Giới tính" },
      { key: "t_dvi", label: "Đơn vị / Bộ môn" },
      { key: "t_tdcmon", label: "Học vị" },
      { key: "t_hham", label: "Học hàm" },
      { key: "t_cmdtao", label: "Chuyên môn" },
      { key: "email", label: "Email" },
    ],
  },
  assignments: {
    label: "Phân công giảng dạy",
    key: "assignments",
    fields: [
      { key: "hocKy", label: "Học kỳ" },
      { key: "maMon", label: "Mã môn học" },
      { key: "tenMon", label: "Tên môn học" },
      { key: "loaiHP", label: "Loại học phần" },
      { key: "soTC", label: "Số tín chỉ" },
      { key: "maGV", label: "Mã GV" },
      { key: "tenGV", label: "Họ tên GV" },
      { key: "hocVi", label: "Học vị" },
      { key: "hocHam", label: "Học hàm" },
      { key: "nganh", label: "Ngành / Chương trình" },
    ],
  },
  grades: {
    label: "Kết quả học tập",
    key: "grades",
    fields: [
      { key: "maHocVien", label: "Mã học viên" },
      { key: "hoTen", label: "Họ tên học viên" },
      { key: "maMon", label: "Mã môn" },
      { key: "tenMon", label: "Tên môn" },
      { key: "diemQT", label: "Điểm quá trình" },
      { key: "diemThi", label: "Điểm thi" },
      { key: "diemTK", label: "Điểm tổng kết" },
      { key: "xepLoai", label: "Xếp loại" },
      { key: "hocKy", label: "Học kỳ" },
    ],
  },
  schedule: {
    label: "Thời khóa biểu",
    key: "schedule",
    fields: [
      { key: "hocKy", label: "Học kỳ" },
      { key: "maMon", label: "Mã môn" },
      { key: "tenMon", label: "Tên môn" },
      { key: "soTC", label: "Số TC" },
      { key: "maGV", label: "Mã GV" },
      { key: "tenGV", label: "Họ tên GV" },
      { key: "thoiGian", label: "Thời gian học" },
      { key: "phong", label: "Phòng / Online" },
      { key: "nganh", label: "Ngành" },
    ],
  },
};